plugins {
id 'com.android.application'

}

android {
namespace "fake.launcher"
compileSdk 29

lint {
        checkReleaseBuilds false
    }

defaultConfig {  
    applicationId "fake.launcher"  
    minSdk 29
    targetSdk 37
    versionCode 1
    versionName "1.0"  
}  

buildTypes {  
    release {  
        minifyEnabled false  
        shrinkResources false  
         }  
}

}

dependencies {
}
